version: '3.3'
services:
  server:
    image: virtualwolf/pi-home-dashboard-server:latest
    ports:
      - 3001:3000
    restart: unless-stopped
    volumes:
      - ./config.json:/opt/service/config.json
